<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Helpdeskultimate
 * @version    2.10.11
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
    $deps = $this->getDepartments();
	$orderCollection = $this->getreturnticketdetail();
	$orderCategory = $this->getcategory();
	$orderSubcategory = $this->getSubCategories();
	//print_r(get_class($this));
	
?>
<script type="text/javascript">
jQuery.noConflict();
jQuery(document).ready(function()
{
jQuery("#category").change(function()
{
var id=jQuery(this).val();
var dataString = 'id='+ id;

jQuery.ajax
({
type: "POST",
url: "<?php echo $this->getUrl('helpdeskultimate/customer/getSubCategories') ?>",
data: dataString,
cache: false,
success: function(html)
{
jQuery("#sub_category").html(html);
} 
});

});

});
</script>
<style>
.item-container {
    background: none repeat scroll 0 0 #E8EBE8;
    height: 174px;
    margin-top: 10px;
    padding: 10px;
    width: 515px;
}
.item-fields {
    float: left;
    width: 85%;
}
.item-qty {
    float: right;
    position: relative;
    width: 15%;
}
.text-qty {
    width: 50px;
}
.remove {
    left: 75%;
    position: absolute;
    text-decoration: none;
    top: 0;
}
.green-box {
    background-color: #35B6F2;
    border: 1px solid #003F5F;
    color: #fff;
    line-height: 1.5;
    margin-bottom: 10px;
    padding: 10px;
	height: 105px;
}
.loade {
    background: none repeat scroll 0 0 #FFF4E9;
    bottom: -4px;
    height: 14%;
    opacity: 0.5;
    position: absolute;
    right: 0;
    width: 10%;
}
#contactForm .button { background:none;}
#contactForm .button span {
    background: url("<?php echo $this->getSkinUrl('images/btn_checkout_2.png') ?>") no-repeat scroll left top; padding-left:18px; float:left;
}
#contactForm .button span span { background-position:right top; padding:0 20px 0 0;}
.std ul{list-style:none !important;}


#overlay {
position: fixed;
top: 0;
left: 0;
width: 100%;
height: 100%;
background-color: #000;
filter:alpha(opacity=70);
-moz-opacity:0.4;
-khtml-opacity: 0.4;
opacity: 0.4;
z-index: 99999;
display: none;
}
.cnt223 a{
text-decoration: none;
}
.popup{
width: 100%;
margin: 0 auto;
display: none;
position: fixed;
z-index: 999999;
top:100px;
left:0px;
}
.cnt223{
min-width: 600px;
width: 600px;
min-height: 150px;
margin: 100px auto;
background: #f3f3f3;
position: relative;
z-index: 103;
padding: 10px 20px;
border:3px solid #ffcc00;
border-radius:5px;
box-shadow: 0 2px 2px #000;
}
.cnt223 p{
clear: both;
text-align: justify;
}

.cnt223 p strong{
font-size: 16px;
}

.cnt223 p a{
color: #2688e3;;
font-weight: bold;
}
.cnt223 p span{
font-weight:bold;
}
.cnt223 .x{
	height: 35px;
    position: absolute;
    right: -12px;
    top: -12px;
    width: 34px;
}
.cnt223 .x:hover{
cursor: pointer;
}
</style>


<div id="messages_product_view">
	<?php if(isset($_SESSION['re_success_msg']) && ($_SESSION['re_success_msg'] == 1)): ?>
		
		<script type='text/javascript'>
		jQuery(function(){
		var overlay = jQuery('<div id="overlay"></div>');
		overlay.show();
		overlay.appendTo(document.body);
		jQuery('.popup').show();
		jQuery('.close').click(function(){
		jQuery('.popup').hide();
		overlay.appendTo(document.body).remove();
		return false;
		});

		jQuery('.x').click(function(){
		jQuery('.popup').hide();
		overlay.appendTo(document.body).remove();
		return false;
		});
		});
		</script>
		<div class='popup'>
			<div class='cnt223'>
				<img src='http://www.developertips.net/demos/popup-dialog/img/x.png' alt='quit' class='x' id='x' />
				<p><strong>Thank You for Submitting Your Ticket!</strong></p>
				<p>Your ticket has been successfully created.</p>	
				<p>Your Ticket confirmation number is <span><a href="<?php echo Mage::getBaseUrl();?>helpdeskultimate/customer/view/id/<?php echo $_SESSION['ticket_id'];?>/"><?php echo $_SESSION['ticket_uid'];?></a></span>.</p>	
				<p>You will receive an email shortly with details of what to expect next and our team of specialist will follow up with you as soon as possible or within 24-48 hours.</p>	
				
					<br/>
					<br/>
				<button class="button close" title="Got It" type="button" id="submit"><span><span>GOT IT!</span></span>
			</div>
		</div>
		
		<?php unset($_SESSION['re_success_msg']) ?>
	<?php endif; ?>
	<?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>
<?php /* ?><div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Return Request Form') ?></h1>
</div><?php */ ?>
<div>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-us-header')->toHTML();?>
</div>
<div style="position: relative;">
	<form action="<?php echo $this->getUrl('contacts/index/post/') ?>" id="contactForm" method="post" enctype="multipart/form-data">
		<div class="fieldset">
			<h2 class="legend"><?php echo Mage::helper('contacts')->__('Return Request Information') ?></h2>
			<ul class="form-list">
				<li class="fields">
					<div class="field">
						<label for="name" class="required"><em>*</em>First Name</label>
						<div class="input-box">
							<input name="name" id="name" title="Name" value="<?php echo $orderCollection[0]['customer_firstname']?>" class="input-text required-entry" type="text" />
						</div>
					</div>
					<div class="field">
						<label for="email" class="required"><em>*</em>Last Name</label>
						<div class="input-box">
							<input name="lname" id="lname" title="lname" value="<?php echo $orderCollection[0]['customer_lastname']?>" class="input-text required-entry" type="text" />
							<input name="wherefrom" id="wherefrom" title="wherefrom" value="returnticket" type="hidden" />
						</div>
					</div>
				</li>
				<li>
					<div class="field">
						<label for="telephone">Telephone</label>
						<div class="input-box">
							<input name="telephone" id="telephone" title="Telephone" value="" class="input-text" type="text" />
						</div>
					</div>
					<div class="field">
						<label for="email" class="required"><em>*</em>Email</label>
						<div class="input-box">
							<input name="email" id="email" title="Email" value="<?php echo $orderCollection[0]['customer_email']?>" class="input-text required-entry validate-email" type="text" />
						</div>
					</div>					
				</li>
				<li class="fields">
					<input type="hidden" id="form-name" name="form-name" value="return" />
					<input type="hidden" id="newformticket" name="newformticket" value="yes" />
				</li>
				<li>
					<div class="item-fields">
						<div>
							<label >Reason For Return</label>
							<div class="input-box">
								<select name="category" id="category" >
									<option>Select One...</option>
									<option value="1">COVER DOESNT FIT</option>
							  <!-- <option value="12">COVER DOESN'T FIT (EXCHANGE)</option> -->
									<option value="8">Defective Item</option>
									<option value="5">Wrong Color / Wrong Item Sent</option>
									<option value="2">Waiting on Cover / Cover Never Shipped</option>
									<option value="9">Quality</option>
									<option value="3">Waiting on Return Label</option>
									<option value="4">Waiting on Refund</option>
									<option value="7">Warranty</option>
									<option value="6">Missing Items</option>
									<option value="10">Other</option>
								</select>
							</div>
						</div>
						<div id="sub_category">
							
						</div>
						
					</div>
					
				</li>
				<li class="wide">
					<label for="additional-comment" >Please provide any additional comments or information we need to know to best assist you.</label>
					<div class="input-box">
						<textarea name="additional_comment" id="additional-comment" title="Comment"  cols="5" rows="3"></textarea>
						<textarea name="comment" id="comment" title="Comment"  cols="5" rows="3" style="display:none;">Comment</textarea>
					</div>
				</li>
				<li>
					<div style="float: left; width: 15%;"><label >You can also attach pictures here </label ></div>
					<div style="float: left; width: 30%;">
						<label for="filename">Attachment (2Mb limit)</label><br/>
						<input class="input-file" name="filename" id="filename" style="width: 450px;" type="file"/>
					</div>
					<div style="float: left; width: 40%;">
						<label for="filename1">Attachment (2Mb limit)</label><br/>
						<input class="input-file" name="filename1" id="filename1" style="width: 450px;" type="file"/>
					</div>
				</li>
				<li><input type="hidden" id="form-name" name="form-name" value="return" />
				</li>
			</ul>
			<p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
			<input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
				<button id="submit-form" type="button" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button" ><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span>
		</div>
		
		<div class="buttons-set" style="display: none;">
			<p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
			<div class="green-box">
                <p style="text-align: left;">Please make sure you check the form for accuracy before hitting the submit button. We will use the information in this form to process your request; inaccuracies or missing information can delay processing.</p>
				<input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
				<button id="submit-button" type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
			</div>
		</div>
		
	</form>
	<img id="loader" alt="Loading" src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" style="left: 400px; position: absolute; top: 70px; display: none;" />
	<div class="loade" style="display: none;"></div>
</div>
<script type="text/javascript">
			document.observe("dom:loaded", function() {
				var antibot = document.createElement('input');
				var d = new Date();
				antibot.setAttribute('type', 'hidden');
				antibot.setAttribute('name', 'antibot-field');
				antibot.setAttribute('value', 'antibot-' + d.getMilliseconds());
				$('contactForm').appendChild(antibot);
			});
		</script>
<script type="text/javascript">
    //<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
    //]]>
	
	jQuery.noConflict();
	jQuery(document).ready(function(){
		jQuery('#submit-form').click(function(){
		
				
		
			 if (contactForm.validator.validate()) {
				jQuery('#loader').show();
				jQuery('.loade').show();
				jQuery("#contactForm").submit();
				//jQuery.post("<?php echo $this->getUrl('helpdeskultimate/customer/getreturnmail') ?>", {name: jQuery('#name').val(), lname: jQuery('#lname').val(), email: jQuery('#email').val()}, function(data){
					//alert( "Data Loaded: " + data );
					//var result = eval("(" + data + ")");
					//jQuery('.form-list').append(result.html);
					//if(result.status == 1){
					//	jQuery('.error-div').hide();
					//	jQuery('#submit-form').parent().hide();
					//	jQuery('#submit-button').parent().parent().show();
					//}
					jQuery('#loader').hide();
					jQuery('.loade').hide();
				//});
			}
		});
		jQuery('.remove').live('click', function(){
			jQuery(this).parent().parent().parent().remove();
		});
	});
	
</script>

<?php $menuContent = Mage::helper('custommenu')->getMenuContent(); ?>
<script type="text/javascript">
//<![CDATA[
$('custommenu').update(<?php echo Zend_Json::encode($menuContent); ?>);
//]]>
</script>
<?php $mobileMenuContent = Mage::helper('custommenu')->getMobileMenuContent(); ?>
<script type="text/javascript">
//<![CDATA[
$('menu-content').update(<?php echo Zend_Json::encode($mobileMenuContent); ?>);
</script>
